{% set version = "0.7.2" %}

package:
  name: pint
  version: {{ version }}

source:
  fn: Pint-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/P/Pint/Pint-{{version}}.tar.gz
  md5: 1e57f7631bb456cdca53e0bdecbc4456

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pint

about:
  home: https://github.com/hgrecco/pint
  license: BSD 3-Clause
  summary: 'Physical quantities module'

extra:
  recipe-maintainers:
    - dopplershift
