{% set name = "pint" %}
{% set version = "0.25.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pint/pint-{{ version }}.tar.gz
  sha256: f8f5df6cf65314d74da1ade1bf96f8e3e4d0c41b51577ac53c49e7d44ca5acee

build:
  number: 0
  skip: true  # [py<312]
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pint-convert = pint.pint_convert:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - platformdirs >=2.1.0
    - flexcache >=0.3
    - flexparser >=0.4
    - typing_extensions >=4.0.0

test:
  requires:
    - pip
  imports:
    - pint
  commands:
    - pip check
    - pint-convert --help

about:
  home: https://github.com/hgrecco/pint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Operate and manipulate physical quantities in Python
  dev_url: https://github.com/hgrecco/pint
  doc_url: https://pint.readthedocs.org/

extra:
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/109074
  recipe-maintainers:
    - amaloney
