travis:
  secure:
    BINSTAR_TOKEN: wHme06HRGmqzpJJoYGRwKO0CiS+d/j7lNg6BPRvQrTxMq5bQS3pU/+loWhAVyYZ92tqGCS9Ml1JC284UDQKLquMb2EPAGRVa+RF1NA1epKufc97gdg6ksodWs6cG+ZB09uXaXGeziPRKKuvloBsGuzUh9sgmyGtkwF93bZKKVV0E9q6huV5hbkErsyj24nd92EEcgEA4z5sr1UlwWh/6tmLq7vdQg1M4P1ec0B/BkYrZVvs9hgL972BSrTmVsnYgfxmAPRv4Xo/Hq817TVXqmTS3evjLOCtvZsq6200J7oiusQViGQCJBj/Nvu/nV9XpD0Ftt+hjMG+NGMnaucLBPGJfanhoniojswIbaC9dLzhyw/8H1kSiqoKE/pMSeCxnbqqWpS/6Hg/Z9CIDnghft5pOcilRZrTzbe06S7HvFIj9Hxv2Jsryc56xhmFouhC8nQWcJ02pmssFXmRJIWQ+W1YNcYeJ+1/2vNyXmE0gfoq6wznzZpcId4XGfp5f8bxZgXv/5AkDjCkBvQo+taPha+gmGrs1c01RCRLQzCbDeMKpEejFpN3O1KBP/qaLpP0uZa4/WW2t4b3/lbb1EdJ8wzMUFZG3nflWMuRLwdLtXOXS7oQ/bO4zewpm1ZhbCMVEkjyICaCCJG+9Xmrvv1xqwynw6ENfoWdJBSytuHcXup0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
