travis:
  secure:
    BINSTAR_TOKEN: ULyyqyttRR/vCxscxAFe//onkv4BvAgLZ61kFVceLN4+aXsGR+pYzCLZB3tpSonJGCWjN/ie9Uf2MLMWv3EFZCxXlZySXm+/Kiz12c09OTJV6Picb+5l4+KiEGImWE7lwVBGFRpF57xxPYxJash7PMkX8Zfh2VW7NDEPWapjacRzBmWWefQYqRBrcKDw0S1QRnxF36CBri3E2Ry/V616dnw8w2ZM6vwRnRUTVarjQMxxzHAMSzPw2lTLvPRTnL2EiXfUSPO9e2vyxpXnOe2YjyCm9gG+0LHQQBHSemn5H0r4IvduhHkhOwLq6A7lE0V0K9+qFnGnAW4woyuLoXSbFJMcT/M975Is3j2RUkmtwef34qu50eY1Nt9HvkX8t8GxhZHCAq6zOq22cnfBSo7R0IWJSBD1A9/3hBnrjv1GmaKJZIz/7tTawyoQvim+m3Jb7J9hFfbouFy/fZ2/9npi40L6ncutkawqi6MoaNcpJtgBo56cGb7HWv23cTYaZI/aBbFXOFkBjL9ySMo1zdF3RTNJxyUj010+COO5ooUdfj2Jw7P4q7WoPxiU2UC0dIxMV5Y9vgzmRSP3f9cTKf1vJ5tfXPa+bxW7HqrJEHzGuxokoH3Q/om7jeoBazKHtZ9pyVCRsrRD0TBzMkXOPCD16ICLXtUabdtJnSS2Bikp7oo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
